
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

## !USE TEXT THEME
# theme: jekyll-text-theme
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

## Base settings ##
# url:  #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: Xiaoming's blog
description: > #this means to ignore newlines until "nav_lists:"
  Xiaoming's Blog
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/Zerowxm/Zerowxm.github.io/master/images/avator.jpg

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: zerowxm@gmail.com
  facebook: wu.xiaoming.988
  flickr:
  github: Zerowxm
  instagram:
  linkedin: wxmzero
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 2885313060ab4ee
  stackoverflow: users/4648457/zero
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: u/0/103551148472099112083

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

paths:
  base: /
  home: /
  all:  /all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
# repository:  #e.g. someone/someone.github.io
# repository_tree:  #e.g. master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
# timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Xiaoming
  email:  zerowxm@gmail.com
  facebook:  wu.xiaoming.988
  twitter:  #your Twitter username
  github:  Zerowxm
  googleplus:  103551148472099112083
  weibo:  #your Weibo username
  douban:  #your Douban username
  linkedin:  wxmzero

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: zerowxm-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-110986578-1
disqus:
  shortname: zerowxm-github-io

## Google Analytics ##
ga_tracking_id: UA-110986578-1
## Reading quantity (LeanCloud) ##
leancloud:
  # app_id:  #LeanCloud App id
  # app_key:  #LeanCloud App key
  # app_class:  #LeanCloud App class

# mathjax: true

## Paginate ##
paginate: 5
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: text # text | html

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
port: 4001
## Development ##
isdebug: false
